CREATE ROLE crucible LOGIN PASSWORD 'crucible' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT CONNECT, TEMPORARY ON DATABASE crucible_target TO crucible;
\connect crucible_target
GRANT USAGE, CREATE ON SCHEMA public TO crucible;
